services:
  - type: web
    name: ALPHA-MD
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
    ports:
      - port: 5000
